language: node_js
node_js:
  - "0.10"
  - "0.11"
script: wget https://github.com/breach/releases/raw/master/exo_browser/v0.6.1916/exo_browser-v0.6.1916-linux-x64.tar.gz && make dist_linux ARCH=x64 EXO_BROWSER=./exo_browser-v0.6.1916-linux-x64.tar.gz NO_GPG_SIGN=true
